name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["latest"]
        ghc: ["8.8", "8.10", "latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        id: haskell-setup
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal update
      - run: cabal freeze
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.haskell-setup.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal build
      - run: cabal test

